name: C25 EMA50 Scan

on:
  workflow_dispatch:

  schedule:
    - cron: "15 15 * * 1-5"

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install pandas yfinance

      - name: Run scanner
        env:
          SMTP_SERVER: send.one.com
          SMTP_PORT: 587
          EMAIL: mgl@godtfredlarsen.com
        run: |
          python c25_ema_scan.py
